import type { PaymentNotificationId } from '@nexus/modules/payment-notifications';

export type PaymentNotificationIdGenerator = () => PaymentNotificationId;

export const PAYMENT_NOTIFICATION_REPOSITORY = Symbol(
  'PAYMENT_NOTIFICATION_REPOSITORY',
);

export const PAYMENT_NOTIFICATION_ID_GENERATOR = Symbol(
  'PAYMENT_NOTIFICATION_ID_GENERATOR',
);

export const PAYMENT_NOTIFICATION_CLOCK = Symbol('PAYMENT_NOTIFICATION_CLOCK');

export const PAYMENT_NOTIFICATION_STATE_TRANSITION = Symbol(
  'PAYMENT_NOTIFICATION_STATE_TRANSITION',
);

export const GET_PAYMENT_NOTIFICATION_BY_ID_USE_CASE = Symbol(
  'GET_PAYMENT_NOTIFICATION_BY_ID_USE_CASE',
);

export const LIST_CUSTOMER_PAYMENT_NOTIFICATIONS_USE_CASE = Symbol(
  'LIST_CUSTOMER_PAYMENT_NOTIFICATIONS_USE_CASE',
);

export const ADMIN_GET_PAYMENT_NOTIFICATION_BY_ID_USE_CASE = Symbol(
  'ADMIN_GET_PAYMENT_NOTIFICATION_BY_ID_USE_CASE',
);

export const ADMIN_LIST_PAYMENT_NOTIFICATIONS_BY_CUSTOMER_USE_CASE = Symbol(
  'ADMIN_LIST_PAYMENT_NOTIFICATIONS_BY_CUSTOMER_USE_CASE',
);

export const CREATE_DRAFT_PAYMENT_NOTIFICATION_USE_CASE = Symbol(
  'CREATE_DRAFT_PAYMENT_NOTIFICATION_USE_CASE',
);

export const UPDATE_PAYMENT_NOTIFICATION_USE_CASE = Symbol(
  'UPDATE_PAYMENT_NOTIFICATION_USE_CASE',
);

export const SUBMIT_PAYMENT_NOTIFICATION_USE_CASE = Symbol(
  'SUBMIT_PAYMENT_NOTIFICATION_USE_CASE',
);

export const START_REVIEW_PAYMENT_NOTIFICATION_USE_CASE = Symbol(
  'START_REVIEW_PAYMENT_NOTIFICATION_USE_CASE',
);

export const VALIDATE_PAYMENT_NOTIFICATION_USE_CASE = Symbol(
  'VALIDATE_PAYMENT_NOTIFICATION_USE_CASE',
);

export const REJECT_PAYMENT_NOTIFICATION_USE_CASE = Symbol(
  'REJECT_PAYMENT_NOTIFICATION_USE_CASE',
);

export const REQUEST_CHANGES_PAYMENT_NOTIFICATION_USE_CASE = Symbol(
  'REQUEST_CHANGES_PAYMENT_NOTIFICATION_USE_CASE',
);

export const RESUBMIT_PAYMENT_NOTIFICATION_USE_CASE = Symbol(
  'RESUBMIT_PAYMENT_NOTIFICATION_USE_CASE',
);
