import { Module } from '@nestjs/common';

import { DataverseModule } from '../dataverse';
import { PAYMENT_NOTIFICATION_PROVIDERS } from './payment-notifications.providers';
import {
  CREATE_DRAFT_PAYMENT_NOTIFICATION_USE_CASE,
  PAYMENT_NOTIFICATION_REPOSITORY,
  REJECT_PAYMENT_NOTIFICATION_USE_CASE,
  REQUEST_CHANGES_PAYMENT_NOTIFICATION_USE_CASE,
  RESUBMIT_PAYMENT_NOTIFICATION_USE_CASE,
  START_REVIEW_PAYMENT_NOTIFICATION_USE_CASE,
  SUBMIT_PAYMENT_NOTIFICATION_USE_CASE,
  UPDATE_PAYMENT_NOTIFICATION_USE_CASE,
  VALIDATE_PAYMENT_NOTIFICATION_USE_CASE,
} from './payment-notifications.tokens';

@Module({
  imports: [DataverseModule],
  providers: PAYMENT_NOTIFICATION_PROVIDERS,
  exports: [
    PAYMENT_NOTIFICATION_REPOSITORY,
    CREATE_DRAFT_PAYMENT_NOTIFICATION_USE_CASE,
    UPDATE_PAYMENT_NOTIFICATION_USE_CASE,
    SUBMIT_PAYMENT_NOTIFICATION_USE_CASE,
    START_REVIEW_PAYMENT_NOTIFICATION_USE_CASE,
    VALIDATE_PAYMENT_NOTIFICATION_USE_CASE,
    REJECT_PAYMENT_NOTIFICATION_USE_CASE,
    REQUEST_CHANGES_PAYMENT_NOTIFICATION_USE_CASE,
    RESUBMIT_PAYMENT_NOTIFICATION_USE_CASE,
  ],
})
export class PaymentNotificationsModule {}
