import { Module } from '@nestjs/common';

import { DataverseModule } from '../dataverse';
import {
  AdminPaymentNotificationsController,
  PaymentNotificationsController,
} from './controllers';
import { PAYMENT_NOTIFICATION_PROVIDERS } from './payment-notifications.providers';
import {
  ADMIN_GET_PAYMENT_NOTIFICATION_BY_ID_USE_CASE,
  ADMIN_LIST_PAYMENT_NOTIFICATIONS_BY_CUSTOMER_USE_CASE,
  CREATE_DRAFT_PAYMENT_NOTIFICATION_USE_CASE,
  GET_PAYMENT_NOTIFICATION_BY_ID_USE_CASE,
  LIST_CUSTOMER_PAYMENT_NOTIFICATIONS_USE_CASE,
  PAYMENT_NOTIFICATION_REPOSITORY,
  REJECT_PAYMENT_NOTIFICATION_USE_CASE,
  REQUEST_CHANGES_PAYMENT_NOTIFICATION_USE_CASE,
  RESUBMIT_PAYMENT_NOTIFICATION_USE_CASE,
  START_REVIEW_PAYMENT_NOTIFICATION_USE_CASE,
  SUBMIT_PAYMENT_NOTIFICATION_USE_CASE,
  UPDATE_PAYMENT_NOTIFICATION_USE_CASE,
  VALIDATE_PAYMENT_NOTIFICATION_USE_CASE,
} from './payment-notifications.tokens';

@Module({
  imports: [DataverseModule],
  controllers: [
    PaymentNotificationsController,
    AdminPaymentNotificationsController,
  ],
  providers: PAYMENT_NOTIFICATION_PROVIDERS,
  exports: [
    PAYMENT_NOTIFICATION_REPOSITORY,
    GET_PAYMENT_NOTIFICATION_BY_ID_USE_CASE,
    LIST_CUSTOMER_PAYMENT_NOTIFICATIONS_USE_CASE,
    ADMIN_GET_PAYMENT_NOTIFICATION_BY_ID_USE_CASE,
    ADMIN_LIST_PAYMENT_NOTIFICATIONS_BY_CUSTOMER_USE_CASE,
    CREATE_DRAFT_PAYMENT_NOTIFICATION_USE_CASE,
    UPDATE_PAYMENT_NOTIFICATION_USE_CASE,
    SUBMIT_PAYMENT_NOTIFICATION_USE_CASE,
    START_REVIEW_PAYMENT_NOTIFICATION_USE_CASE,
    VALIDATE_PAYMENT_NOTIFICATION_USE_CASE,
    REJECT_PAYMENT_NOTIFICATION_USE_CASE,
    REQUEST_CHANGES_PAYMENT_NOTIFICATION_USE_CASE,
    RESUBMIT_PAYMENT_NOTIFICATION_USE_CASE,
  ],
})
export class PaymentNotificationsModule {}
