export const AUTHENTICATED_ACTOR_DATAVERSE_CLIENT = Symbol(
  'AUTHENTICATED_ACTOR_DATAVERSE_CLIENT',
);

export const AUTHENTICATED_ACTOR_GATEWAY = Symbol(
  'AUTHENTICATED_ACTOR_GATEWAY',
);

export const AUTHENTICATED_ACTOR_RESOLVER = Symbol(
  'AUTHENTICATED_ACTOR_RESOLVER',
);
