export const COMMERCIAL_CATALOG_DATAVERSE_CLIENT = Symbol(
  'COMMERCIAL_CATALOG_DATAVERSE_CLIENT',
);

export const COMMERCIAL_CATALOG_PRODUCT_GATEWAY = Symbol(
  'COMMERCIAL_CATALOG_PRODUCT_GATEWAY',
);

export const COMMERCIAL_CATALOG_PRODUCT_REPOSITORY = Symbol(
  'COMMERCIAL_CATALOG_PRODUCT_REPOSITORY',
);

export const COMMERCIAL_CATALOG_CUSTOMER_PRICE_GATEWAY = Symbol(
  'COMMERCIAL_CATALOG_CUSTOMER_PRICE_GATEWAY',
);

export const COMMERCIAL_CATALOG_CUSTOMER_PRICE_REPOSITORY = Symbol(
  'COMMERCIAL_CATALOG_CUSTOMER_PRICE_REPOSITORY',
);

export const COMMERCIAL_CATALOG_CLOCK = Symbol('COMMERCIAL_CATALOG_CLOCK');

export const LIST_CUSTOMER_CATALOG_USE_CASE = Symbol(
  'LIST_CUSTOMER_CATALOG_USE_CASE',
);

export const GET_CUSTOMER_CATALOG_ITEM_USE_CASE = Symbol(
  'GET_CUSTOMER_CATALOG_ITEM_USE_CASE',
);
