import { ConfigurationError } from '../server/configuration-error';
import { readEnvironmentVariable } from '../server/environment-reader';
import type { EnvironmentVariables } from '../shared/environment-variables';

export const REQUIRED_AUTHENTICATED_ACTOR_DATAVERSE_ENVIRONMENT_VARIABLES = [
  'DATAVERSE_NEXUS_USER_ENTITY_SET',
  'DATAVERSE_NEXUS_USER_ROLE_ENTITY_SET',
  'DATAVERSE_NEXUS_USER_PERMISSION_ENTITY_SET',
  'DATAVERSE_NEXUS_APPROVAL_GROUP_MEMBER_ENTITY_SET',
  'DATAVERSE_NEXUS_USER_FIELD_OID',
  'DATAVERSE_NEXUS_USER_FIELD_ACTIVE',
  'DATAVERSE_NEXUS_USER_FIELD_CUSTOMER_ID',
  'DATAVERSE_NEXUS_USER_ROLE_FIELD_OID',
  'DATAVERSE_NEXUS_USER_ROLE_FIELD_ROLE',
  'DATAVERSE_NEXUS_USER_PERMISSION_FIELD_OID',
  'DATAVERSE_NEXUS_USER_PERMISSION_FIELD_MODULE',
  'DATAVERSE_NEXUS_USER_PERMISSION_FIELD_ACTION',
  'DATAVERSE_NEXUS_USER_PERMISSION_FIELD_EFFECT',
  'DATAVERSE_NEXUS_APPROVAL_GROUP_MEMBER_FIELD_OID',
  'DATAVERSE_NEXUS_APPROVAL_GROUP_MEMBER_FIELD_APPROVAL_GROUP_ID',
] as const;

export const REQUIRED_ORDERS_DATAVERSE_ENVIRONMENT_VARIABLES = [
  'DATAVERSE_ORDERS_ENTITY_SET',
  'DATAVERSE_ORDERS_FIELD_ID',
  'DATAVERSE_ORDERS_FIELD_CUSTOMER_ID',
  'DATAVERSE_ORDERS_FIELD_STATUS',
  'DATAVERSE_ORDERS_FIELD_CURRENCY_CODE',
  'DATAVERSE_ORDERS_FIELD_SUBTOTAL',
  'DATAVERSE_ORDERS_FIELD_CREATED_AT',
  'DATAVERSE_ORDERS_FIELD_UPDATED_AT',
  'DATAVERSE_ORDER_LINES_ENTITY_SET',
  'DATAVERSE_ORDER_LINES_FIELD_ID',
  'DATAVERSE_ORDER_LINES_FIELD_ORDER_ID',
  'DATAVERSE_ORDER_LINES_FIELD_PRODUCT_ID',
  'DATAVERSE_ORDER_LINES_FIELD_PRODUCT_NUMBER',
  'DATAVERSE_ORDER_LINES_FIELD_PRODUCT_NAME',
  'DATAVERSE_ORDER_LINES_FIELD_UNIT_OF_MEASURE_CODE',
  'DATAVERSE_ORDER_LINES_FIELD_CURRENCY_CODE',
  'DATAVERSE_ORDER_LINES_FIELD_QUANTITY',
  'DATAVERSE_ORDER_LINES_FIELD_UNIT_PRICE',
  'DATAVERSE_ORDER_LINES_FIELD_LINE_SUBTOTAL',
] as const;

export const REQUIRED_FINANCE_CUSTOMER_REFERENCE_DATAVERSE_ENVIRONMENT_VARIABLES =
  [
    'DATAVERSE_FINANCE_CUSTOMER_ENTITY_SET',
    'DATAVERSE_FINANCE_CUSTOMER_FIELD_NEXUS_CUSTOMER_ID',
    'DATAVERSE_FINANCE_CUSTOMER_FIELD_BUSINESS_CENTRAL_CUSTOMER_ID',
    'DATAVERSE_FINANCE_CUSTOMER_FIELD_ACTIVE',
  ] as const;

export const REQUIRED_COMMERCIAL_CATALOG_DATAVERSE_ENVIRONMENT_VARIABLES = [
  'DATAVERSE_COMMERCIAL_CATALOG_PRODUCT_ENTITY_SET',
  'DATAVERSE_COMMERCIAL_CATALOG_PRODUCT_FIELD_ID',
  'DATAVERSE_COMMERCIAL_CATALOG_PRODUCT_FIELD_NUMBER',
  'DATAVERSE_COMMERCIAL_CATALOG_PRODUCT_FIELD_NAME',
  'DATAVERSE_COMMERCIAL_CATALOG_PRODUCT_FIELD_DESCRIPTION',
  'DATAVERSE_COMMERCIAL_CATALOG_PRODUCT_FIELD_CATEGORY_ID',
  'DATAVERSE_COMMERCIAL_CATALOG_PRODUCT_FIELD_IMAGE_REFERENCE',
  'DATAVERSE_COMMERCIAL_CATALOG_PRODUCT_FIELD_UNIT_OF_MEASURE_CODE',
  'DATAVERSE_COMMERCIAL_CATALOG_PRODUCT_FIELD_ECOMMERCE_URL',
  'DATAVERSE_COMMERCIAL_CATALOG_PRODUCT_FIELD_ACTIVE',
  'DATAVERSE_COMMERCIAL_CATALOG_PRICE_ENTITY_SET',
  'DATAVERSE_COMMERCIAL_CATALOG_PRICE_FIELD_ID',
  'DATAVERSE_COMMERCIAL_CATALOG_PRICE_FIELD_CUSTOMER_ID',
  'DATAVERSE_COMMERCIAL_CATALOG_PRICE_FIELD_PRODUCT_ID',
  'DATAVERSE_COMMERCIAL_CATALOG_PRICE_FIELD_CURRENCY_CODE',
  'DATAVERSE_COMMERCIAL_CATALOG_PRICE_FIELD_UNIT_PRICE',
  'DATAVERSE_COMMERCIAL_CATALOG_PRICE_FIELD_MINIMUM_QUANTITY',
  'DATAVERSE_COMMERCIAL_CATALOG_PRICE_FIELD_VALID_FROM',
  'DATAVERSE_COMMERCIAL_CATALOG_PRICE_FIELD_VALID_TO',
  'DATAVERSE_COMMERCIAL_CATALOG_PRICE_FIELD_ACTIVE',
] as const;

export const REQUIRED_DATAVERSE_ENVIRONMENT_VARIABLES = [
  'DATAVERSE_ENVIRONMENT_URL',
  'DATAVERSE_PAYMENT_NOTIFICATION_ENTITY_SET',
  'DATAVERSE_PAYMENT_NOTIFICATION_INVOICE_ENTITY_SET',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_CUSTOMER_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_STATUS',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_PAYMENT_DATE',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_AMOUNT',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_CURRENCY',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_BANK_REFERENCE',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_RECEIPT_FILE_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_CREATED_AT',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_UPDATED_AT',
  'DATAVERSE_PAYMENT_NOTIFICATION_INVOICE_FIELD_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_INVOICE_FIELD_PAYMENT_NOTIFICATION_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_INVOICE_FIELD_INVOICE_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_INVOICE_FIELD_CREATED_AT',
  ...REQUIRED_AUTHENTICATED_ACTOR_DATAVERSE_ENVIRONMENT_VARIABLES,
  ...REQUIRED_FINANCE_CUSTOMER_REFERENCE_DATAVERSE_ENVIRONMENT_VARIABLES,
  ...REQUIRED_COMMERCIAL_CATALOG_DATAVERSE_ENVIRONMENT_VARIABLES,
  ...REQUIRED_ORDERS_DATAVERSE_ENVIRONMENT_VARIABLES,
] as const;

type DataverseEnvironmentVariable =
  (typeof REQUIRED_DATAVERSE_ENVIRONMENT_VARIABLES)[number];

export type ValidatedDataverseEnvironment = Readonly<
  Record<DataverseEnvironmentVariable, string>
>;

export const validateDataverseEnvironment = (
  environment: EnvironmentVariables = process.env,
): ValidatedDataverseEnvironment => {
  const entries = REQUIRED_DATAVERSE_ENVIRONMENT_VARIABLES.map(
    (variableName) =>
      [
        variableName,
        readEnvironmentVariable(variableName, environment),
      ] as const,
  );
  const missingVariables = entries
    .filter(([, value]) => value === undefined)
    .map(([variableName]) => variableName);

  if (missingVariables.length > 0) {
    throw new ConfigurationError(missingVariables);
  }

  return Object.freeze(
    Object.fromEntries(entries) as ValidatedDataverseEnvironment,
  );
};
