import { ConfigurationError } from '../server/configuration-error';
import { readEnvironmentVariable } from '../server/environment-reader';
import type { EnvironmentVariables } from '../shared/environment-variables';

export const REQUIRED_AUTHENTICATED_ACTOR_DATAVERSE_ENVIRONMENT_VARIABLES = [
  'DATAVERSE_NEXUS_USER_ENTITY_SET',
  'DATAVERSE_NEXUS_USER_ROLE_ENTITY_SET',
  'DATAVERSE_NEXUS_USER_PERMISSION_ENTITY_SET',
  'DATAVERSE_NEXUS_APPROVAL_GROUP_MEMBER_ENTITY_SET',
  'DATAVERSE_NEXUS_USER_FIELD_OID',
  'DATAVERSE_NEXUS_USER_FIELD_ACTIVE',
  'DATAVERSE_NEXUS_USER_FIELD_CUSTOMER_ID',
  'DATAVERSE_NEXUS_USER_ROLE_FIELD_OID',
  'DATAVERSE_NEXUS_USER_ROLE_FIELD_ROLE',
  'DATAVERSE_NEXUS_USER_PERMISSION_FIELD_OID',
  'DATAVERSE_NEXUS_USER_PERMISSION_FIELD_MODULE',
  'DATAVERSE_NEXUS_USER_PERMISSION_FIELD_ACTION',
  'DATAVERSE_NEXUS_USER_PERMISSION_FIELD_EFFECT',
  'DATAVERSE_NEXUS_APPROVAL_GROUP_MEMBER_FIELD_OID',
  'DATAVERSE_NEXUS_APPROVAL_GROUP_MEMBER_FIELD_APPROVAL_GROUP_ID',
] as const;

export const REQUIRED_DATAVERSE_ENVIRONMENT_VARIABLES = [
  'DATAVERSE_ENVIRONMENT_URL',
  'DATAVERSE_PAYMENT_NOTIFICATION_ENTITY_SET',
  'DATAVERSE_PAYMENT_NOTIFICATION_INVOICE_ENTITY_SET',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_CUSTOMER_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_STATUS',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_PAYMENT_DATE',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_AMOUNT',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_CURRENCY',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_BANK_REFERENCE',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_RECEIPT_FILE_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_CREATED_AT',
  'DATAVERSE_PAYMENT_NOTIFICATION_FIELD_UPDATED_AT',
  'DATAVERSE_PAYMENT_NOTIFICATION_INVOICE_FIELD_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_INVOICE_FIELD_PAYMENT_NOTIFICATION_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_INVOICE_FIELD_INVOICE_ID',
  'DATAVERSE_PAYMENT_NOTIFICATION_INVOICE_FIELD_CREATED_AT',
  ...REQUIRED_AUTHENTICATED_ACTOR_DATAVERSE_ENVIRONMENT_VARIABLES,
] as const;

type DataverseEnvironmentVariable =
  (typeof REQUIRED_DATAVERSE_ENVIRONMENT_VARIABLES)[number];

export type ValidatedDataverseEnvironment = Readonly<
  Record<DataverseEnvironmentVariable, string>
>;

export const validateDataverseEnvironment = (
  environment: EnvironmentVariables = process.env,
): ValidatedDataverseEnvironment => {
  const entries = REQUIRED_DATAVERSE_ENVIRONMENT_VARIABLES.map(
    (variableName) =>
      [
        variableName,
        readEnvironmentVariable(variableName, environment),
      ] as const,
  );
  const missingVariables = entries
    .filter(([, value]) => value === undefined)
    .map(([variableName]) => variableName);

  if (missingVariables.length > 0) {
    throw new ConfigurationError(missingVariables);
  }

  return Object.freeze(
    Object.fromEntries(entries) as ValidatedDataverseEnvironment,
  );
};
