export const BUSINESS_CENTRAL_ACCESS_TOKEN_PROVIDER = Symbol(
  'BUSINESS_CENTRAL_ACCESS_TOKEN_PROVIDER',
);

export const BUSINESS_CENTRAL_HTTP_CLIENT = Symbol(
  'BUSINESS_CENTRAL_HTTP_CLIENT',
);

export const BUSINESS_CENTRAL_INVOICE_GATEWAY = Symbol(
  'BUSINESS_CENTRAL_INVOICE_GATEWAY',
);

export const BUSINESS_CENTRAL_CREDIT_MEMO_GATEWAY = Symbol(
  'BUSINESS_CENTRAL_CREDIT_MEMO_GATEWAY',
);

export const FINANCE_INVOICE_REPOSITORY = Symbol('FINANCE_INVOICE_REPOSITORY');

export const FINANCE_CREDIT_MEMO_REPOSITORY = Symbol(
  'FINANCE_CREDIT_MEMO_REPOSITORY',
);

export const FINANCE_CUSTOMER_REFERENCE_DATAVERSE_CLIENT = Symbol(
  'FINANCE_CUSTOMER_REFERENCE_DATAVERSE_CLIENT',
);

export const FINANCE_CUSTOMER_REFERENCE_GATEWAY = Symbol(
  'FINANCE_CUSTOMER_REFERENCE_GATEWAY',
);

export const FINANCE_CUSTOMER_REFERENCE_RESOLVER = Symbol(
  'FINANCE_CUSTOMER_REFERENCE_RESOLVER',
);

export const GET_FINANCE_INVOICE_BY_ID_USE_CASE = Symbol(
  'GET_FINANCE_INVOICE_BY_ID_USE_CASE',
);

export const LIST_CUSTOMER_FINANCE_INVOICES_USE_CASE = Symbol(
  'LIST_CUSTOMER_FINANCE_INVOICES_USE_CASE',
);

export const GET_FINANCE_CREDIT_MEMO_BY_ID_USE_CASE = Symbol(
  'GET_FINANCE_CREDIT_MEMO_BY_ID_USE_CASE',
);

export const LIST_CUSTOMER_FINANCE_CREDIT_MEMOS_USE_CASE = Symbol(
  'LIST_CUSTOMER_FINANCE_CREDIT_MEMOS_USE_CASE',
);
